/*  Lista com todos as faixas de consumidores de todas as classes
presentes na norma ND 5.1 da CEMIG */


export default {
    customerNull: [
        {
            band: null,
            minLoad: null, maxLoad: null,
            qtdWires: null,
            fases: null,
            circuitBreakerNEMA: null, circuitBreakerDIN: null,
            conductingWire: null,
            conduitPVC: null, conduitSteel: null,
            groundingWire: null,
            qtdGroundingElectrode: null,
            protectiveWire: null,
            poleSameSideSteel: null,
            poleSameSideConcrete: null,
            poleOppositeSideSteel: null,
            poleOppositeSideConcrete: null,
            mast: null
        }
    ],

    customerA: [
        {
            band: 'A1',
            minLoad: 0, maxLoad: 5,
            qtdWires: 2,
            fases: 1,
            circuitBreakerNEMA: 40, circuitBreakerDIN: 40,
            conductingWire: 6,
            conduitPVC: 32, conduitSteel: 25,
            groundingWire: 10,
            qtdGroundingElectrode: 1,
            protectiveWire: 6,
            poleSameSideSteel: 'PA1',
            poleSameSideConcrete: 'PC1',
            poleOppositeSideSteel: 'PA4',
            poleOppositeSideConcrete: 'PC2',
            mast: 'PT1'
        },

        {
            band: 'A2',
            minLoad: 5, maxLoad: 6.5,
            qtdWires: 2,
            fases: 1,
            circuitBreakerNEMA: 50, circuitBreakerDIN: 50,
            conductingWire: 10,
            conduitPVC: 32, conduitSteel: 25,
            groundingWire: 10,
            qtdGroundingElectrode: 1,
            protectiveWire: 10,
            poleSameSideSteel: 'PA1',
            poleSameSideConcrete: 'PC1',
            poleOppositeSideSteel: 'PA4',
            poleOppositeSideConcrete: 'PC2',
            mast: 'PT1'
        },

        {
            band: 'A3',
            minLoad: 6.5, maxLoad: 10,
            qtdWires: 2,
            fases: 1,
            circuitBreakerNEMA: 70, circuitBreakerDIN: 63,
            conductingWire: 16,
            conduitPVC: 32, conduitSteel: 25,
            groundingWire: 10,
            qtdGroundingElectrode: 1,
            protectiveWire: 16,
            poleSameSideSteel: 'PA1',
            poleSameSideConcrete: 'PC1',
            poleOppositeSideSteel: 'PA4',
            poleOppositeSideConcrete: 'PC2',
            mast: 'PT1'
        },

    ],

    customerB: [

        {
            band: 'B1',
            minLoad: 0, maxLoad: 10,
            qtdWires: 3,
            fases: 2,
            circuitBreakerNEMA: 40, circuitBreakerDIN: 40,
            conductingWire: 10,
            conduitPVC: 32, conduitSteel: 25,
            groundingWire: 10,
            qtdGroundingElectrode: 1,
            protectiveWire: 10,
            poleSameSideSteel: 'PA1',
            poleSameSideConcrete: 'PC1',
            poleOppositeSideSteel: 'PA4',
            poleOppositeSideConcrete: 'PC2',
            mast: 'PT1'
        },

        {
            band: 'B2',
            minLoad: 10, maxLoad: 15,
            qtdWires: 3,
            fases: 2,
            circuitBreakerNEMA: 60, circuitBreakerDIN: 63,
            conductingWire: 16,
            conduitPVC: 32, conduitSteel: 25,
            groundingWire: 10,
            qtdGroundingElectrode: 1,
            protectiveWire: 16,
            poleSameSideSteel: 'PA1',
            poleSameSideConcrete: 'PC1',
            poleOppositeSideSteel: 'PA4',
            poleOppositeSideConcrete: 'PC2',
            mast: 'PT1'
        },

    ],

    customerC: [
        {
            band: 'C1',
            minLoad: 0, maxLoad: 15,
            qtdWires: 4,
            fases: 3,
            circuitBreakerNEMA: 40, circuitBreakerDIN: 40,
            conductingWire: 10,
            conduitPVC: 32, conduitSteel: 25,
            groundingWire: 10,
            qtdGroundingElectrode: 2,
            protectiveWire: 10,
            poleSameSideSteel: 'PA1',
            poleSameSideConcrete: 'PC1',
            poleOppositeSideSteel: 'PA4',
            poleOppositeSideConcrete: 'PC2',
            mast: 'PT1'
        },

        {
            band: 'C2',
            minLoad: 0, maxLoad: 23,
            qtdWires: 4,
            fases: 3,
            circuitBreakerNEMA: 60, circuitBreakerDIN: 63,
            conductingWire: 16,
            conduitPVC: 32, conduitSteel: 25,
            groundingWire: 10,
            qtdGroundingElectrode: 2,
            protectiveWire: 16,
            poleSameSideSteel: 'PA1',
            poleSameSideConcrete: 'PC1',
            poleOppositeSideSteel: 'PA4',
            poleOppositeSideConcrete: 'PC2',
            mast: 'PT1'
        },

        {
            band: 'C3',
            minLoad: 23, maxLoad: 27,
            qtdWires: 4,
            fases: 3,
            circuitBreakerNEMA: 70, circuitBreakerDIN: 80,
            conductingWire: 25,
            conduitPVC: 40, conduitSteel: 32,
            groundingWire: 10,
            qtdGroundingElectrode: 2,
            protectiveWire: 16,
            poleSameSideSteel: 'PA1',
            poleSameSideConcrete: 'PC1',
            poleOppositeSideSteel: 'PA4',
            poleOppositeSideConcrete: 'PC2',
            mast: 'PT1'
        },

        {
            band: 'C4',
            minLoad: 27, maxLoad: 38,
            qtdWires: 4,
            fases: 3,
            circuitBreakerNEMA: 100, circuitBreakerDIN: 100,
            conductingWire: 35,
            conduitPVC: 40, conduitSteel: 32,
            groundingWire: 10,
            qtdGroundingElectrode: 2,
            protectiveWire: 16,
            poleSameSideSteel: 'PA2',
            poleSameSideConcrete: 'PC1',
            poleOppositeSideSteel: 'PA5',
            poleOppositeSideConcrete: 'PC2',
            mast: 'PT1'
        },

        {
            band: 'C5',
            minLoad: 38, maxLoad: 47,
            qtdWires: 4,
            fases: 3,
            circuitBreakerNEMA: 120, circuitBreakerDIN: 125,
            conductingWire: 50,
            conduitPVC: 50, conduitSteel: 40,
            groundingWire: 10,
            qtdGroundingElectrode: 2,
            protectiveWire: 25,
            poleSameSideSteel: 'PA2',
            poleSameSideConcrete: 'PC1',
            poleOppositeSideSteel: 'PA5',
            poleOppositeSideConcrete: 'PC2',
            mast: 'PT1'
        },

        {
            band: 'C6',
            minLoad: 47, maxLoad: 57,
            qtdWires: 4,
            fases: 3,
            circuitBreakerNEMA: 150, circuitBreakerDIN: 150,
            conductingWire: 70,
            conduitPVC: 60, conduitSteel: 50,
            groundingWire: 10,
            qtdGroundingElectrode: 3,
            protectiveWire: 35,
            poleSameSideSteel: 'PA3',
            poleSameSideConcrete: 'PC3',
            poleOppositeSideSteel: 'PA6',
            poleOppositeSideConcrete: 'PC3',
            mast: 'PT2'
        },

        {
            band: 'C7',
            minLoad: 57, maxLoad: 66,
            qtdWires: 4,
            fases: 3,
            circuitBreakerNEMA: 175, circuitBreakerDIN: 175,
            conductingWire: 95,
            conduitPVC: 75, conduitSteel: 65,
            groundingWire: 10,
            qtdGroundingElectrode: 3,
            protectiveWire: 35,
            poleSameSideSteel: 'PA3',
            poleSameSideConcrete: 'PC3',
            poleOppositeSideSteel: 'PA6',
            poleOppositeSideConcrete: 'PC3',
            mast: 'PT2'
        },

        {
            band: 'C8',
            minLoad: 66, maxLoad: 75,
            qtdWires: 4,
            fases: 3,
            circuitBreakerNEMA: 200, circuitBreakerDIN: 200,
            conductingWire: 95,
            conduitPVC: 75, conduitSteel: 65,
            groundingWire: 10,
            qtdGroundingElectrode: 3,
            protectiveWire: 35,
            poleSameSideSteel: 'PA3',
            poleSameSideConcrete: 'PC3',
            poleOppositeSideSteel: 'PA6',
            poleOppositeSideConcrete: 'PC3',
            mast: 'PT2'
        },
    ],

    customerD: [
        {
            band: 'D1',
            minLoad: 0, maxLoad: 9.6,
            qtdWires: 3,
            fases: 2,
            circuitBreakerNEMA: 40, circuitBreakerDIN: 40,
            conductingWire: 10,
            conduitPVC: 32, conduitSteel: 25,
            groundingWire: 10,
            qtdGroundingElectrode: 1,
            protectiveWire: 10,
            poleSameSideSteel: 'PA4',
            poleSameSideConcrete: 'PC2',
            poleOppositeSideSteel: 'PA4',
            poleOppositeSideConcrete: 'PC2',
            mast: '-',
            powerTransformer: '5 ou 10'
        },
        {
            band: 'D2',
            minLoad: 0, maxLoad: 12,
            qtdWires: 3,
            fases: 2,
            circuitBreakerNEMA: 50, circuitBreakerDIN: 50,
            conductingWire: 16,
            conduitPVC: 32, conduitSteel: 25,
            groundingWire: 10,
            qtdGroundingElectrode: 1,
            protectiveWire: 16,
            poleSameSideSteel: 'PA4',
            poleSameSideConcrete: 'PC2',
            poleOppositeSideSteel: 'PA4',
            poleOppositeSideConcrete: 'PC2',
            mast: '-',
            powerTransformer: '5 ou 10'
        },
        {
            band: 'D3',
            minLoad: 0, maxLoad: 14.4,
            qtdWires: 3,
            fases: 2,
            circuitBreakerNEMA: 60, circuitBreakerDIN: 63,
            conductingWire: 16,
            conduitPVC: 32, conduitSteel: 25,
            groundingWire: 10,
            qtdGroundingElectrode: 1,
            protectiveWire: 16,
            poleSameSideSteel: 'PA4',
            poleSameSideConcrete: 'PC2',
            poleOppositeSideSteel: 'PA4',
            poleOppositeSideConcrete: 'PC2',
            mast: '-',
            powerTransformer: '10'
        },
        {
            band: 'D4',
            minLoad: 0, maxLoad: 16.8,
            qtdWires: 3,
            fases: 2,
            circuitBreakerNEMA: 70, circuitBreakerDIN: 80,
            conductingWire: 25,
            conduitPVC: 40, conduitSteel: 32,
            groundingWire: 10,
            qtdGroundingElectrode: 2,
            protectiveWire: 16,
            poleSameSideSteel: 'PA5',
            poleSameSideConcrete: 'PC2',
            poleOppositeSideSteel: 'PA5',
            poleOppositeSideConcrete: 'PC2',
            mast: '-',
            powerTransformer: '15'
        },
        {
            band: 'D5',
            minLoad: 0, maxLoad: 24,
            qtdWires: 3,
            fases: 2,
            circuitBreakerNEMA: 100, circuitBreakerDIN: 100,
            conductingWire: 35,
            conduitPVC: 40, conduitSteel: 32,
            groundingWire: 10,
            qtdGroundingElectrode: 2,
            protectiveWire: 16,
            poleSameSideSteel: 'PA5',
            poleSameSideConcrete: 'PC2',
            poleOppositeSideSteel: 'PA5',
            poleOppositeSideConcrete: 'PC2',
            mast: '-',
            powerTransformer: '25'
        },
        {
            band: 'D6',
            minLoad: 0, maxLoad: 36,
            qtdWires: 3,
            fases: 2,
            circuitBreakerNEMA: 150, circuitBreakerDIN: 150,
            conductingWire: 70,
            conduitPVC: 60, conduitSteel: 50,
            groundingWire: 10,
            qtdGroundingElectrode: 3,
            protectiveWire: 35,
            poleSameSideSteel: 'PA6',
            poleSameSideConcrete: 'PC3',
            poleOppositeSideSteel: 'PA6',
            poleOppositeSideConcrete: 'PC3',
            mast: '-',
            powerTransformer: '37.5'
        },
        {
            band: 'D7',
            minLoad: 0, maxLoad: 50,
            qtdWires: 3,
            fases: 2,
            circuitBreakerNEMA: null, circuitBreakerDIN: 200,
            conductingWire: 95,
            conduitPVC: 75, conduitSteel: 65,
            groundingWire: 10,
            qtdGroundingElectrode: 3,
            protectiveWire: 35,
            poleSameSideSteel: 'PA6',
            poleSameSideConcrete: 'PC3',
            poleOppositeSideSteel: 'PA6',
            poleOppositeSideConcrete: 'PC3',
            mast: '-',
            powerTransformer: '37.5'
        },
    ],

    customerE: [
        {
            band: 'E1',
            minLoad: 0, maxLoad: 15,
            qtdWires: 4,
            fases: 3,
            circuitBreakerNEMA: 60, circuitBreakerDIN: 63,
            conductingWire: 16,
            conduitPVC: 40, conduitSteel: 32,
            groundingWire: 10,
            qtdGroundingElectrode: 2,
            protectiveWire: 16,
            poleSameSideSteel: 'PA4',
            poleSameSideConcrete: 'PC2',
            poleOppositeSideSteel: 'PA4',
            poleOppositeSideConcrete: 'PC2',
            mast: '-',
            powerTransformer: 'Transformador Exclusivo'
        },
        {
            band: 'E2',
            minLoad: 15, maxLoad: 30,
            qtdWires: 4,
            fases: 3,
            circuitBreakerNEMA: 90, circuitBreakerDIN: 100,
            conductingWire: 35,
            conduitPVC: 40, conduitSteel: 32,
            groundingWire: 10,
            qtdGroundingElectrode: 2,
            protectiveWire: 16,
            poleSameSideSteel: 'PA5',
            poleSameSideConcrete: 'PC2',
            poleOppositeSideSteel: 'PA5',
            poleOppositeSideConcrete: 'PC2',
            mast: '-',
            powerTransformer: 'Transformador Exclusivo'
        },
        {
            band: 'E3',
            minLoad: 30, maxLoad: 45,
            qtdWires: 4,
            fases: 3,
            circuitBreakerNEMA: 120, circuitBreakerDIN: 125,
            conductingWire: 50,
            conduitPVC: 50, conduitSteel: 40,
            groundingWire: 10,
            qtdGroundingElectrode: 2,
            protectiveWire: 25,
            poleSameSideSteel: 'PA5',
            poleSameSideConcrete: 'PC2',
            poleOppositeSideSteel: 'PA5',
            poleOppositeSideConcrete: 'PC2',
            mast: '-',
            powerTransformer: 'Transformador Exclusivo'
        },
        {
            band: 'E4',
            minLoad: 45, maxLoad: 75,
            qtdWires: 4,
            fases: 3,
            circuitBreakerNEMA: 200, circuitBreakerDIN: 125,
            conductingWire: 95,
            conduitPVC: 75, conduitSteel: 65,
            groundingWire: 10,
            qtdGroundingElectrode: 3,
            protectiveWire: 50,
            poleSameSideSteel: 'PA6',
            poleSameSideConcrete: 'PC3',
            poleOppositeSideSteel: 'PA6',
            poleOppositeSideConcrete: 'PC3',
            mast: '-',
            powerTransformer: 'Transformador Exclusivo'
        }
    ],

    customerF: [
        {
            band: 'F1',
            minLoad: 75, maxLoad: 86,
            qtdWires: 4,
            fases: 3,
            circuitBreakerNEMA: '-', circuitBreakerDIN: 225,
            conductingWire: 16,
            conduitPVC: 40, conduitSteel: 32,
            groundingWire: 10,
            qtdGroundingElectrode: 2,
            protectiveWire: 16,
            poleSameSideSteel: 'PA4',
            poleSameSideConcrete: 'PC2',
            poleOppositeSideSteel: 'PA4',
            poleOppositeSideConcrete: 'PC2',
            mast: '-',
            powerTransformer: 'Transformador Exclusivo'
        },
    ]
}
